; Global defaults applied to all models
[*]
gpu-layers = auto
flash-attn = on
tensor-read-lazy = auto

[Qwen3.8-Flash-Next-IQ4_XS]
model = B:\models\Qwen3.8-Flash-Next-UD-IQ4_XS\UD-IQ4_XS\Qwen3.8-Flash-Next-UD-IQ4_XS-00001-of-00003.gguf
alias = qwen3.8-flash-next,qwen4exp
gpu-layers = 99
cpu-moe = true
tensor-split = 1,1
ctx-size = 100000
parallel = 1
load-mode = none
mmproj = B:\models\Qwen3.8-Flash-Next-UD-IQ4_XS\mmproj-F16.gguf

[Qwen3.8-Flash-Next-Uncensored-GGUF]
alias = qwen4exp-uncensored
gpu-layers = 99
cpu-moe = true
tensor-split = 1,1
ctx-size = 100000
parallel = 1
load-mode = none
